services:

  antdev-blog:
    container_name: antdev-webapp
    environment:
      ENV: local
      PORT: 8080
      LOG_FORMAT: "TEXT"
      USE_LOCAL_STORAGE_COMMENTS: "1"
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"