services:

  antdev-blog:
    container_name: antdev-webapp
    environment:
      PORT: 8080
      USE_LOCAL_STORAGE_COMMENTS: "1"
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"