// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar flex justify-between items-center p-8 dark:text-white dark:bg-slate-800\"><div class=\"font-normal inline-flex items-center\"><img alt=\"placeholder\" src=\"https://avatars.githubusercontent.com/u/39270163?s=400&amp;u=fda2d106649deed081695cc4fd086dcc85211b99&amp;v=4\" width=\"80\" height=\"100\" class=\"rounded-full\"> <a class=\"ml-3 text-3xl italic dark:text-white\" href=\"/\">ant.dev</a></div><div class=\"flex space-x-8\"><a class=\"font-normal hover:font-bold\" href=\"/\">Home</a> <a class=\"font-normal hover:font-bold\" href=\"/articles\">Articles</a> <a class=\"font-normal hover:font-bold\" href=\"/about\">About</a> <a class=\"font-normal hover:font-bold\" href=\"/contact\">Contact</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
