// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar flex justify-between items-center p-4 dark:text-white dark:bg-slate-800\"><div class=\"font-normal inline-flex items-center ml-4\"><img alt=\"placeholder\" src=\"https://avatars.githubusercontent.com/u/39270163?s=400&amp;u=fda2d106649deed081695cc4fd086dcc85211b99&amp;v=4\" width=\"40\" height=\"60\" class=\"rounded-full\"> <a class=\"ml-2 pt-2 text-2xl italic dark:text-white\" href=\"/\">ant.dev</a></div><div class=\"hidden md:flex space-x-8 mr-4\"><a class=\"font-normal hover:font-bold\" href=\"/\">Home</a> <a class=\"font-normal hover:font-bold\" href=\"/articles\">Articles</a> <a class=\"font-normal hover:font-bold\" href=\"/about\">About</a> <a class=\"font-normal hover:font-bold\" href=\"/contact\">Contact</a></div><div class=\"relative md:hidden group\"><div class=\"cursor-pointer mr-4\">Menu</div><div class=\"absolute right-0 hidden flex-col bg-slate-800 mt-2 rounded-lg shadow-lg group-hover:flex group-hover:mt-0\"><a class=\"block px-4 py-2 text-sm text-white hover:bg-slate-700\" href=\"/\">Home</a> <a class=\"block px-4 py-2 text-sm text-white hover:bg-slate-700\" href=\"/articles\">Articles</a> <a class=\"block px-4 py-2 text-sm text-white hover:bg-slate-700\" href=\"/about\">About</a> <a class=\"block px-4 py-2 text-sm text-white hover:bg-slate-700\" href=\"/contact\">Contact</a></div></div></nav><hr>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
