name: Deploy Webapp

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - 'infrastructure/**'
      - 'test/**'

  workflow_dispatch:

env:
  SERVICE_NAME: "antdev-webapp"
  PORT: 8080

jobs:

  continuous-deployment:
    environment: production
    runs-on: ubuntu-latest

    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2.6.0'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: 'gcr.io/cloudrun/hello'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
      
